import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";
import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";

const notoKufi = Noto_Kufi_Arabic({
	subsets: ["arabic", "latin"],
	weight: ["500", "700"],
	variable: "--font-noto-kufi",
});

export const metadata: Metadata = {
	title: "Bahrain Forum",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ar">
			<body className={`bg-background ${notoKufi.variable} antialiased `}>
				<Theme grayColor="mauve">
					<div className="bg-background h-screen">{children}</div>
				</Theme>
			</body>
		</html>
	);
}
