import type { Metadata } from "next";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Noto_Kufi_Arabic } from "next/font/google";
import "./globals.css";
import SidebarLeft from "./assets/components/layout/SidebarLeft";
import SidebarRight from "./assets/components/layout/SidebarRight";
import NavBar from "./assets/components/layout/NavBar";

const notoKufi = Noto_Kufi_Arabic({
	subsets: ["arabic", "latin"],
	weight: ["500", "700"],
	variable: "--font-noto-kufi",
});

export const metadata: Metadata = {
	title: "Bahrain Forum",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ar">
			<body className={`bg-background ${notoKufi.variable} antialiased `}>
				<Theme grayColor="mauve">
					<div className="h-screen bg-background grid grid-cols-7 gap-6">
						<NavBar />
						<SidebarLeft />
						{children}
						<SidebarRight />
					</div>
				</Theme>
			</body>
		</html>
	);
}
